language: python
python: 3.6
branches:
  except: /^v\.\d\.\d\.\d/
before_install: pip install babel
install: pip install --upgrade .
script: 
  - submit50 --help
  - python setup.py compile_catalog
before_deploy: |
  version="v$(submit50 --version | cut --delimiter ' ' --fields 2)"
  if [ -z "$(git tag --list "$version")" ]; then \
      git config --local user.name "bot50"; \
      git config --local user.email "bot@cs50.harvard.edu"; \
      git tag "$version"; \
  fi
deploy:
- provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    branch: master
- provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: DHyiOOI74L9aIi2raGNpsGpyNC5STBci9HvL22l+ujl0h4rcT3fg50Gj9tTtvlKsJwe+gGMx8nXwZZRO/d6uuBlr5Sez3DcBaQbC5YRJQDAxorL4R8ay+2hGtU00dMzH4mtfJwiH9lISfXf+L5nXDqisckN6KtcwHh8hRrK6wjU35D035aIKoWvKcZYA5hhc9uE6D+LV+mVMr7AK9mUDUl3kpzbc9KChRgjyP893rpEKInVbQeZtpT96v0/yyM3ef1l+x9trw7dHZWy2OfXcP4VG6SFywCls8vt4fAeIm50mpHOr11R6QScRmjB562xVt3BU1fwKjSv57nZ/N7IiNAQ97WY8LAanHQQosfESahHbXYFQ0RpPVXfdwEhQetlUuh32w5uJNqZ0Nx/CjoMO4cToTeNsYCeCIIFNKjlFLfbfuJsGqWxb3g9EgtRAYhVQSok1fNPJNbfx3SfA5ZhCFv1t8HGZADXrN0wRPblygVSyG1ELUb3KWbdQ5XtE5S+Dr2r2YVcbrVgc6OQ60g6CowItzcz91K2DFbWyUQoSHMH6iLrqa3hOBRCKsnv4YBRwn0O5B4+KmfuJBz+xj1qmlUw7YAWMmu2PUoM/X9NS+NTzE85IyQY2/KTWeqK02ixyKPqj8+vqsC8mLEz9PHJjQcaBWaGIQUNTDNIKHcUtDVA=
